library(shinydashboard)
library(shiny)
library(summarytools)
library(plotly)
library(devtools)
library(DT)
library(GGally)
library(psych)
library(ggbiplot)
library(ggcorrplot)
library(caret)
library(pls)
library(tidyverse)
library(shinycssloaders)
library(factoextra)
library(Amelia)
library("corrplot")
library("FactoMineR")
mt <- read.csv("mtcars.csv")
bt <- read.csv("Boston.csv")

inputchoice <- c("mpg", "cyl",  "disp",  "hp", "drat", "wt", "qsec", "gear", "carb")
inputchoice1 <- c("Comp.1","Comp.2","Comp.3","Comp.4","Comp.5","Comp.6","Comp.7","Comp.8","Comp.9","Comp.10","Comp.11")
inputchoice2 <- c("ward.D","ward.D2","single","complete","average","mcquitty","median","centroid")